"""
DisposableEmailService — blocks known disposable/temp email providers.
Extend the DISPOSABLE_DOMAINS set to add more domains.
"""

DISPOSABLE_DOMAINS = {
    # Common disposable email providers
    "mailinator.com", "guerrillamail.com", "guerrillamail.info", "guerrillamail.org",
    "guerrillamail.net", "guerrillamail.de", "guerrillamail.biz", "guerrillamailblock.com",
    "10minutemail.com", "10minutemail.net", "10minutemail.org", "10minutemail.co.uk",
    "10minutemail.us", "10minutemail.de", "10minutemail.it", "10minutemail.ru",
    "tempmail.com", "tempmail.net", "tempmail.org", "temp-mail.org", "temp-mail.io",
    "temp-mail.ru", "tmpmail.net", "tmpmail.org",
    "throwam.com", "throwaway.email", "throwam.com",
    "yopmail.com", "yopmail.fr", "yopmail.net", "cool.fr.nf", "jetable.fr.nf",
    "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr", "courriel.fr.nf",
    "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
    "trashmail.com", "trashmail.me", "trashmail.net", "trashmail.org",
    "trashmail.at", "trashmail.io", "trashmail.xyz",
    "mailnull.com", "mailnull.net",
    "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
    "fakeinbox.com", "fakeinbox.net",
    "dispostable.com", "dispostable.net",
    "mailnesia.com", "mailnesia.net",
    "mailforspam.com",
    "spambog.com", "spambog.de", "spambog.ru",
    "spam4.me",
    "binkmail.com",
    "bob.email",
    "clrmail.com",
    "dontreg.com",
    "drdrb.com",
    "e4ward.com",
    "emailisvalid.com",
    "emailtemporario.com.br",
    "getonemail.com", "getonemail.net",
    "giantmail.de",
    "girlsundertheinfluence.com",
    "h8s.org",
    "haltospam.com",
    "hatespam.org",
    "hidemail.de",
    "incognitomail.com", "incognitomail.net", "incognitomail.org",
    "inoutmail.de",
    "jetable.com", "jetable.net", "jetable.org", "jetable.fr",
    "junk1.com",
    "klassmaster.com",
    "klassmaster.net",
    "klzlk.com",
    "kurzepost.de",
    "lifebyfood.com",
    "link2mail.net",
    "litedrop.com",
    "lol.ovpn.to",
    "maildrop.cc",
    "mailexpire.com",
    "mailf5.com",
    "mailfreeonline.com",
    "mailguard.me",
    "mailinater.com",
    "mailmetrash.com",
    "mailmoat.com",
    "mailnew.com",
    "mailnull.com",
    "mailpick.biz",
    "mailrock.biz",
    "mailscrap.com",
    "mailshell.com",
    "mailsiphon.com",
    "mailslite.com",
    "mailzilla.com", "mailzilla.org",
    "mbx.cc",
    "mega.zik.dj",
    "meltmail.com",
    "mierdamail.com",
    "mintemail.com",
    "mjukglass.nu",
    "moakt.com",
    "moaktmail.com",
    "moncourrier.fr.nf",
    "monmail.fr.nf",
    "msa.minsmail.com",
    "mt2009.com",
    "mx0.wwwnew.eu",
    "my10minutemail.com",
    "mytrashmail.com",
    "neomailbox.com",
    "nepwk.com",
    "nervmich.net",
    "nervtmich.net",
    "netmails.com", "netmails.net",
    "netzidiot.de",
    "nico.dtdns.net",
    "nincsmail.hu",
    "no-spam.ws",
    "nobulk.com",
    "noclickemail.com",
    "nogmailspam.info",
    "nomail.pw",
    "nomail.xl.cx",
    "nomail2me.com",
    "nomorespamemails.com",
    "nonspam.eu",
    "nonspammer.de",
    "nospam.ze.tc",
    "nospamfor.us",
    "nospammail.net",
    "notmailinator.com",
    "nowmymail.com",
    "nwldx.com",
    "objectmail.com",
    "obobbo.com",
    "odnorazovoe.ru",
    "oneoffemail.com",
    "onewaymail.com",
    "oopi.org",
    "ora.pm",
    "owlpic.com",
    "pjjkp.com",
    "plexolan.de",
    "pookmail.com",
    "privatdemail.net",
    "proxymail.eu",
    "prtnx.com",
    "punkass.com",
    "qq.com",  # Sometimes abused
    "quickinbox.com",
    "rcpt.at",
    "recode.me",
    "recursor.net",
    "regbypass.com", "regbypass.comsafe-mail.net",
    "regspaces.tk",
    "rejectmail.com",
    "rklips.com",
    "rmqkr.net",
    "rppkn.com",
    "rtrtr.com",
    "s0ny.net",
    "safe-mail.net",
    "safetymail.info",
    "safetypost.de",
    "sandelf.de",
    "saynotospams.com",
    "selfdestructingmail.com",
    "sendspamhere.com",
    "sharklasers.com",
    "shieldedmail.com",
    "shiftmail.com",
    "shitmail.me",
    "shitmail.org",
    "shortmail.net",
    "sibmail.com",
    "skeefmail.com",
    "slopsbox.com",
    "slushmail.com",
    "smashmail.de",
    "snkmail.com",
    "sofimail.com",
    "sofort-mail.de",
    "sogetthis.com",
    "soodonims.com",
    "spam-en.de",
    "spam-und-schinken.de",
    "spam.la",
    "spam.su",
    "spamavert.com",
    "spamcowboy.com", "spamcowboy.net", "spamcowboy.org",
    "spamday.com",
    "spamex.com",
    "spamfree.eu",
    "spamfree24.de", "spamfree24.eu", "spamfree24.info", "spamfree24.net", "spamfree24.org",
    "spamgoes.in",
    "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
    "spamherelots.com",
    "spamhereplease.com",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com", "spaml.de",
    "spammotel.com",
    "spamobox.com",
    "spamoff.de",
    "spamslicer.com",
    "spamspot.com",
    "spamstack.net",
    "spamthis.co.uk",
    "spamthisplease.com",
    "spamtroll.net",
    "spamwc.de",
    "spamz.de",
    "speed.1s.fr",
    "spoofmail.de",
    "spycamera.info",
    "squizzy.de", "squizzy.eu", "squizzy.net",
    "ss00.cf", "ss00.ga", "ss00.gq", "ss00.ml", "ss00.tk",
    "ss01.cf", "ss01.ga", "ss01.gq", "ss01.ml", "ss01.tk",
    "stinkefinger.net",
    "stuffmail.de",
    "super-auswahl.de",
    "supergreatmail.com",
    "supermailer.jp",
    "superrito.com",
    "superstachel.de",
    "suremail.info",
    "tafmail.com",
    "tagyourself.com",
    "teewars.org",
    "teleworm.com", "teleworm.us",
    "temporaryemail.net",
    "temporaryforwarding.com",
    "temporaryinbox.com",
    "temporarymail.org",
    "tempr.email",
    "tempsky.com",
    "tempthe.net",
    "thanksnospam.info",
    "thisisnotmyrealemail.com",
    "throam.com",
    "throwam.com",
    "tilien.com",
    "tmail.com",
    "tmailinator.com",
    "toiea.com",
    "toomail.biz",
    "topranklist.de",
    "tradermail.info",
    "trash-mail.at", "trash-mail.com", "trash-mail.de", "trash-mail.ga", "trash-mail.io",
    "trash-mail.ml", "trash-mail.tk",
    "trash2009.com", "trash2010.com", "trash2011.com",
    "trashdevil.com", "trashdevil.de",
    "trashemail.de",
    "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.io",
    "trashmail.me", "trashmail.net", "trashmail.org", "trashmail.xyz",
    "trashmailer.com",
    "trashtigers.com",
    "trbvm.com",
    "turual.com",
    "twinmail.de",
    "tyldd.com",
    "uggsrock.com",
    "umail.net",
    "uroid.com",
    "us.af",
    "veryrealemail.com",
    "vidchart.com",
    "viditag.com",
    "viewcastmedia.com", "viewcastmedia.net", "viewcastmedia.org",
    "vinernet.com",
    "vipmail.pw",
    "viralplays.com",
    "vkcode.ru",
    "vmani.com",
    "vomoto.com",
    "vpn.st",
    "vsimcard.com",
    "vubby.com",
    "walala.org",
    "walkmail.net",
    "wam.co.za",
    "webemail.me",
    "weg-werf-email.de",
    "wegwerf-emails.de",
    "wegwerfadresse.de",
    "wegwerfemail.com", "wegwerfemail.de", "wegwerfemail.net",
    "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org",
    "wetrainbayarea.com", "wetrainbayarea.org",
    "wh4f.org",
    "whatpaas.com",
    "whyspam.me",
    "willhackforfood.biz",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "www.e4ward.com",
    "wwwnew.eu",
    "x.ip6.li",
    "xagloo.co", "xagloo.com",
    "xemaps.com",
    "xents.com",
    "xmaily.com",
    "xoxox.cc",
    "xoxy.net",
    "xyzfree.net",
    "yapped.net",
    "yep.it",
    "yertxenor.tk",
    "yogamaven.com",
    "yopmail.com", "yopmail.fr", "yopmail.info", "yopmail.net",
    "you-spam.com",
    "yourdomain.com",
    "yuurok.com",
    "z1p.biz",
    "za.com",
    "zehnminuten.de",
    "zehnminutenmail.de",
    "zippymail.info",
    "zoemail.net", "zoemail.org",
    "zomg.info",
    "zxcv.com",
    "zxcvbnm.com",
}


class DisposableEmailService:
    """
    Checks whether an email domain belongs to a known disposable/temporary email provider.
    Usage:
        service = DisposableEmailService()
        if service.is_disposable("user@mailinator.com"):
            raise HTTPException(400, "Disposable emails not allowed")
    """

    @staticmethod
    def normalize_email(email: str) -> str:
        return email.strip().lower()

    @staticmethod
    def extract_domain(email: str) -> str:
        parts = email.rsplit("@", 1)
        if len(parts) != 2:
            raise ValueError(f"Invalid email format: {email}")
        return parts[1].lower()

    def is_disposable(self, email: str) -> bool:
        """Returns True if the email belongs to a known disposable provider."""
        try:
            normalized = self.normalize_email(email)
            domain = self.extract_domain(normalized)
            return domain in DISPOSABLE_DOMAINS
        except ValueError:
            return False  # Let schema validation handle malformed emails

    def validate(self, email: str) -> None:
        """
        Raises ValueError if the email is from a disposable provider.
        """
        if self.is_disposable(email):
            raise ValueError(
                "Temporary or disposable email addresses are not allowed. "
                "Please use a permanent email address."
            )
